<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-GD2TQ7C" ignored="0" name="Test" tests="8" failures="1" timestamp="10 May 2022 12:44:26 GMT" time="0.08" errors="0">
  <testcase name="textCase07" time="0.016" classname="com.EX.Class1"/>
  <testcase name="textCase08" time="0.016" classname="com.EX.Class1"/>
  <testcase name="textCase04" time="0.024" classname="com.EX.Class1"/>
  <testcase name="testCase03" time="0.024" classname="com.EX.Class1">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at com.EX.Class1.testCase03(Class1.java:19)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- testCase03 -->
  <testcase name="testCase02" time="0.0" classname="com.EX.Class1"/>
  <testcase name="textCase06" time="0.0" classname="com.EX.Class1"/>
  <testcase name="textCase05" time="0.0" classname="com.EX.Class1"/>
  <testcase name="testCase01" time="0.008" classname="com.EX.Class1"/>
</testsuite> <!-- Test -->
